### Importing Packages

In [1]:
import numpy
import scipy
import pprint

from numpy import linalg
from numpy import random
from scipy import linalg

### Note

There are some codes where NumPy, SciPy, and other packages were not used. In some, these packages were only used for checking and comparing results. The author could simply have used them for faster computations but the author wanted to try to solve the problems manually using the built-in functions in Python.

# Solving Systems of Linear Equations

## Matrix Equations as Systems of Linear Equations

For natural-numbered constants ${m, n \in \mathbb{N}}$, a real vector constant ${\vec{\boldsymbol{v}} \in \mathbb{R}^{m}}$, a real vector variable ${\vec{\boldsymbol{x}}}$ in ${\mathbb{R}^{n}}$ of ${n}$ real variables, and a real matrix constant ${\boldsymbol{A} \in \mathbb{R}^{m \times n}}$, a matrix equation given by:

\begin{equation}
    \boldsymbol{A} \vec{\boldsymbol{x}} = \vec{\boldsymbol{v}}
\end{equation}

For ${m = n}$, and the corresponding inverse matrix ${\boldsymbol{A}^{-1} \in \mathbb{R}^{n \times n}}$ of ${\boldsymbol{A}}$, ${\vec{\boldsymbol{x}}}$ is given by:

\begin{equation}
    \boldsymbol{A} \vec{\boldsymbol{x}} = \vec{\boldsymbol{v}} \iff \vec{\boldsymbol{x}} = \boldsymbol{A}^{-1} \vec{\boldsymbol{v}}
\end{equation}

In [2]:
# Generating sample matrices and vectors.
n = 3
A = numpy.random.rand(n, n)
B = numpy.random.rand(n, n)
v = numpy.random.rand(n)
A_upper_triangular = numpy.triu(A)
A_lower_triangular = numpy.tril(A)

test_A = A.tolist()
test_B = B.tolist()
test_v = v.tolist()
test_A_upper_triangular = A_upper_triangular.tolist()
test_A_lower_triangular = A_lower_triangular.tolist()

pprint.pprint(A)
pprint.pprint(A_upper_triangular)
pprint.pprint(A_lower_triangular)
pprint.pprint(B)
pprint.pprint(v)

array([[0.89866404, 0.38397806, 0.07749467],
       [0.71601492, 0.3365267 , 0.41827888],
       [0.04427912, 0.63363696, 0.4658499 ]])
array([[0.89866404, 0.38397806, 0.07749467],
       [0.        , 0.3365267 , 0.41827888],
       [0.        , 0.        , 0.4658499 ]])
array([[0.89866404, 0.        , 0.        ],
       [0.71601492, 0.3365267 , 0.        ],
       [0.04427912, 0.63363696, 0.4658499 ]])
array([[0.47491169, 0.96314375, 0.05172548],
       [0.52966196, 0.6055427 , 0.8530703 ],
       [0.35901652, 0.01995703, 0.81696733]])
array([0.39794781, 0.56561564, 0.6982833 ])


For natural-numbered indices ${i, j \in \mathbb{N}}$ such that ${i, j \leq n}$, real constants ${a_{i, j}, v_{j} \in \mathbb{R}}$ such that ${\boldsymbol{A} = \left( a_{i, j} \right)}$ and ${\vec{\boldsymbol{v}} = \left( v_{j} \right)}$, and real variables ${x_{j}}$ such that ${\vec{\boldsymbol{x}} = \left( x_{j} \right)}$,

The ${n}$-dimensional zero vector ${\vec{\boldsymbol{0}}}$ is defined as:

\begin{equation}
    \vec{\boldsymbol{0}} := \left( v_{j} \right), \quad \forall j \colon \quad v_{j} = 0
\end{equation}

In [3]:
def zero_vector(n):
    """
    Creates an n-dimensional zero vector manually.
    
    where
        n: (int), number of elements.
    """
    result = []
    for i in range(0, n, 1):
        result.append(0.0)
    return result

pprint.pprint(zero_vector(n))

[0.0, 0.0, 0.0]


The ${m}$ by ${n}$ zero matrix ${\boldsymbol{0}}$ is defined as:

\begin{equation}
    \boldsymbol{0} := \left( a_{i, j} \right), \quad \forall i, j \colon \quad a_{i,j} = 0
\end{equation}

In [4]:
def zero_matrix(m, n):
    """
    Creates an m by n zero matrix manually.
    
    where
        m: (int), number of rows.
        n: (int), number of columns.
    """
    result = []
    for i in range(0, m, 1):
        result.append([0.0] * n)
    return result

pprint.pprint(zero_matrix(n, n))

[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]


For the discrete (also called Kronecker) delta function of ${i}$ and ${j}$, the ${n}$-dimensional identity matrix ${\mathbb{1}}$ is defined as:

\begin{equation}
    \mathbb{1} := \left( \delta_{i, j} \right), \quad \delta_{i, j} :=
        \begin{cases}
            \hfill 0, &\quad i \neq j\\
            \hfill 1, &\quad i = j
        \end{cases}
\end{equation}

In [5]:
def identity_matrix(n):
    """
    Creates an n by n identity matrix manually.
    
    where
        n: (int), number of rows and columns.
    """
    result = zero_matrix(n, n)
    for i in range (0, n, 1):
        for j in range(0, n, 1):
            if i == j:
                result[i][j] = 1.0
            else:
                result[i][j] = 0.0
    return result
    
pprint.pprint(identity_matrix(n))

[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]


The matrix product ${\boldsymbol{Av} \in \mathbb{R}^{n}}$ is defined as:

\begin{equation}
    \boldsymbol{Av} := \left( \sum_{j = 1}^{n} \left( a_{i, j} v_{j} \right) \right)
\end{equation}

In [6]:
def multiply_matrix_vector(A, v):
    """
    Multiplies an m by n matrix to an n-dimensional vector v manually.
    
    where
        A: (list), m by n matrix.
        v: (list), n-dimensional vector.
    """
    result = zero_vector(len(A))
    for i in range(0, len(A), 1):
        for j in range(0, len(A), 1):
            result[i] += A[i][j] * v[j]
    return result

print("Using NumPy:")
pprint.pprint(numpy.matmul(A, v))

print("Without using other packages:")
pprint.pprint(multiply_matrix_vector(test_A, test_v))

Using NumPy:
array([0.62891861, 0.76735849, 0.70131096])
Without using other packages:
[0.6289186145444925, 0.7673584893555389, 0.7013109562403288]


For natural-numbered indices ${i, j, k \in \mathbb{N}}$, natural-numbered constants ${m, n, p \in \mathbb{N}}$, real constants ${a_{i, j}, b_{j, k} \in \mathbb{R}}$, two real matrix constants ${\boldsymbol{A} \in \mathbb{R}^{m \times p}}$ and ${\boldsymbol{B} \in \mathbb{R}^{p \times n}}$, the matrix product ${\boldsymbol{AB} \in \mathbb{R}^{m \times n}}$ is defined as:

\begin{equation}
    \boldsymbol{AB} := \left( \sum_{k = 1}^{p} \left( a_{i, k} b_{k, j} \right) \right)
\end{equation}

In [7]:
def multiply_matrix(A, B):
    """
    Multiplies an m by p matrix to an p by n matrix manually.
    
    where
        A: (list), m by p matrix.
        B: (list), p by n matrix.
    """
    result = zero_matrix(len(A), len(B[0]))
    for i in range(0, len(A), 1):
        for j in range(0, len(B[0]), 1):
            for k in range(0, len(B), 1):
                result[i][j] += A[i][k] * B[k][j]
    return result

print("Using NumPy:")
pprint.pprint(numpy.matmul(A, B))

print("Without using other packages:")
pprint.pprint(multiply_matrix(test_A, test_B))

Using NumPy:
array([[0.6579865 , 1.09960434, 0.43735472],
       [0.66845828, 0.90175419, 0.66583733],
       [0.52388987, 0.43563837, 0.92341138]])
Without using other packages:
[[0.6579865037587519, 1.0996043388973769, 0.4373547217550015],
 [0.6684582805288769, 0.9017541937973849, 0.6658373292051585],
 [0.5238898739273191, 0.435638372434521, 0.9234113794388834]]


## Solving Matrix Equations Involving Lower and Upper and Triangular Matrices

${1.}$ If ${\boldsymbol{A}}$ is a lower triangular matrix, then for all ${j > 1}$, ${a_{i, j} = 0}$, and ${x_{i}}$ is given by:

\begin{equation}
    x_{i} = \frac{1}{a_{i, i}} \left( v_{i} - \sum_{k = 1}^{i - 1} \left( a_{i, k} x_{k} \right) \right) \iff x_{1} = \frac{v_{1}}{a_{1, 1}}
\end{equation}

In [8]:
def solve_lower_triangular(A, v):
    """
    Manually solves for x in the matrix equation A x = v.
    
    For n: (int), positive integer, where
        A: (list), an n by n non-singular lower-triangular coefficient matrix.
        v: (list), an n by 1 coefficient matrix.
        x: (list), an n by 1 unknown matrix.
    """
    x = zero_vector(len(v))
    x[0] = v[0] / A[0][0]
    for i in range(1, len(v), 1):
        x[i] = (1 / A[i][i]) * (v[i] - sum(A[i][k] * x[k] for k in range(0, len(v), 1)))
    return x

print("Using SciPy:")
pprint.pprint(scipy.linalg.solve(A_lower_triangular, v))

print("Without using other packages:")
pprint.pprint(solve_lower_triangular(test_A_lower_triangular, test_v))

Using SciPy:
array([0.44282155, 0.73857082, 0.45226967])
Without using other packages:
[0.44282155121895, 0.7385708205342945, 0.4522696723378249]


${2.}$ If ${\boldsymbol{A}}$ is an upper triangular matrix, then for all ${i > j}$, ${a_{i, j} = 0}$, and ${x_{i}}$ is gievn by:

\begin{equation}
    x_{i} = \frac{1}{a_{i, i}} \left( v_{i} - \sum_{k = i + 1}^{n } \left( a_{i, k} x_{k} \right) \right) \iff x_{n} = \frac{v_{n}}{a_{n, n}}
\end{equation}

In [9]:
def solve_upper_triangular(A, v):
    """
    Manually solves for x in the matrix equation A x = v.
    
    For n: (int), positive integer, where
        A: (list), an n by n non-singular upper-triangular coefficient matrix.
        v: (list), an n by 1 coefficient matrix.
        x: (list), an n by 1 unknown matrix.
    """
    x = zero_vector(len(v))
    x[-1] = v[-1] / A[-1][-1]
    for i in range(len(v) - 2, -1, -1):
        x[i] = (1 / A[i][i]) * (v[i] - sum(A[i][k] * x[k] for k in range(len(v) - 1, -1, -1)))
    return x


print("Using SciPy:")
pprint.pprint(scipy.linalg.solve(A_upper_triangular, v))

print("Without using other packages:")
pprint.pprint(solve_upper_triangular(test_A_upper_triangular, test_v))

Using SciPy:
array([ 0.39147115, -0.18233716,  1.49894483])
Without using other packages:
[0.39147114792065335, -0.18233715929217306, 1.4989448294987502]


## Lower-Upper Triangular Matrix Decomposition of a Matrix with Pivoting

For real constants ${l_{i, j}, u_{i, j} \in \mathbb{R}}$, two real matrices ${\boldsymbol{L}, \boldsymbol{U} \in \mathbb{R}^{n \times n}}$ such that ${\boldsymbol{L}}$ is a lower triangular matrix given by ${\boldsymbol{L} = \left( l_{i, j} \right)}$ and ${\boldsymbol{U}}$ is an upper triangular matrix given by ${\boldsymbol{U} = \left( u_{i, j} \right)}$, ${\boldsymbol{A}}$ can be expressed as the matrix product ${\boldsymbol{LU}}$ given by:

\begin{equation}
    \boldsymbol{A} = \boldsymbol{LU} \iff
        \begin{cases}
            \hfill u_{i, j} \mkern-10mu &= a_{i, j} - \displaystyle \sum_{k = 1}^{i - 1} \left( u_{k, j} l_{i, k} \right)\\
            \hfill l_{i, j} \mkern-10mu &= \dfrac{1}{u_{j, j}} \left( a_{i, j} - \displaystyle \sum_{k = 1}^{j - 1} \left( u_{k, j} l_{i, k} \right) \right)
        \end{cases}
\end{equation}



In [10]:
def solve_pivot_lower_upper(A):
    """
    Manually solves for the lower-upper triangular decomposition of a matrix with pivoting.
    
    Where
        A: (list), an n by n non-singular upper-triangular coefficient matrix.
    """
    n = len(A)
    P = identity_matrix(n)
    L = zero_matrix(n, n)
    U = zero_matrix(n, n)
    for j in range(0, n, 1):
        i = max(range(j, n, 1), key = lambda i: abs(A[i][j]))
        if j != i:
            P[j], P[i] = P[i], P[j]
    PA = multiply_matrix(P, A)                                                                                                                                                                                                                    
    for j in range(n):                                                                                                                                                                                 
        for i in range(0, j + 1, 1):
            U[i][j] = PA[i][j] - sum(U[k][j] * L[i][k] for k in range(i))                                                                                                                                                               
        for i in range(j, n, 1):
            L[i][j] = (1 / U[j][j]) * (PA[i][j] - sum(U[k][j] * L[i][k] for k in range(j)))
    return P, L, U

print("Using NumPy and SciPy:")
P1, L1, U1 = scipy.linalg.lu(A)
pprint.pprint(numpy.matmul(L1, U1))

print("Without using other packages:")
P2, L2, U2 = solve_pivot_lower_upper(test_A)
pprint.pprint(P2)
pprint.pprint(L2)
pprint.pprint(U2)
pprint.pprint(multiply_matrix(L2, U2))

Using NumPy and SciPy:
array([[0.89866404, 0.38397806, 0.07749467],
       [0.04427912, 0.63363696, 0.4658499 ],
       [0.71601492, 0.3365267 , 0.41827888]])
Without using other packages:
[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0]]
[[1.0, 0.0, 0.0],
 [0.04927215699162315, 0.9999999999999999, 0.0],
 [0.7967548358052117, 0.04976321898532339, 1.0]]
[[0.8986640426439828, 0.3839780645838825, 0.07749466708859598],
 [0.0, 0.6147175326172449, 0.46203156962763575],
 [0.0, 0.0, 0.3335424511271945]]
[[0.8986640426439828, 0.3839780645838825, 0.07749466708859598],
 [0.04427911579188104, 0.6336369600967615, 0.46584989903043855],
 [0.7160149217408542, 0.3365267029900839, 0.41827888005666103]]


This implies that ${\boldsymbol{A} \vec{\boldsymbol{x}} = \vec{\boldsymbol{v}}}$ is given by:

\begin{align*}
    \boldsymbol{A} \vec{\boldsymbol{x}} = \vec{\boldsymbol{v}} &\iff \boldsymbol{LU} \vec{\boldsymbol{x}} = \vec{\boldsymbol{v}}\\
    &\iff \vec{\boldsymbol{x}} = \boldsymbol{U}^{-1} \boldsymbol{L}^{-1} \vec{\boldsymbol{v}}\\
\end{align*}

In [11]:
def solve_matrix_pivot_lower_upper(A, v):
    """
    Solves for x in the matrix equation A x = v using LU decomposition.
    
    For n: (int), positive integer, where
        A: (list), an n by n non-singular coefficient matrix.
        v: (list), an n by 1 coefficient matrix.
        x: (list), an n by 1 unknown matrix.
    """
    P, L, U = solve_pivot_lower_upper(A)
    Pv = multiply_matrix_vector(P, v)
    x = solve_upper_triangular(U, solve_lower_triangular(L, Pv))
    return x

print("Using SciPy:")
pprint.pprint(scipy.linalg.solve(A, v))

print("Without using other packages:")
pprint.pprint(solve_matrix_pivot_lower_upper(test_A, test_v))

Using SciPy:
array([0.12235625, 0.62006155, 0.6439232 ])
Without using other packages:
[0.12235624663496461, 0.6200615450227276, 0.6439232019257749]
