In [1]:
import numpy as np
import numpy.linalg as la
import numpy.random as ra

# <center> Motivation </center>

Consider the following problem,
\begin{equation}
\mathbf{A} x = c
\end{equation}
where $\mathbf{A}$ is an $N\times N$ matrix and $x$ and $c$ are column vectors. In particular, $x$ is a column vector with unknown components. The solution of this simple matrix equation is simply
\begin{equation}
x = \mathbf{A}^{-1}c.
\end{equation}
where we define
\begin{equation}
\mathbf{A} \cdot \mathbf{A}^{-1} = \mathbf{A}^{-1} \cdot \mathbf{A} = \mathbb{1}
\end{equation}
The elegance of this solution is that most of the computation is not dependent on $c$. Once we know $\mathbf{A}^{-1}$, then we can solve a general class of problems - we just need to plug in $c$!

Naively, the computational complexity of calculating the inverse is $N^3$. There are $N^2$ unknowns, corresponding to the $N\times N$ coefficients of $\mathbf{A}^{-1}$, and one would need to calculate the sum of $N$ products to isolate each uknown via Gaussian elimination.

After $\mathbf{A}^{-1}$, multiplying $\mathbf{A}^{-1}c$ involves $N^2$ operations.
___

However, there are times that computing the inverse of a matrix is unnecessary. We can skip directly to a computation that is $O(N^2)$. Suppose for example $\mathbf{A}$ is in an upper triangular form,
\begin{equation}
\mathbf{A} = \begin{pmatrix}
A_{11} & A_{12} & A_{13} & \dots & A_{1N} \\
0 & A_{22} & A_{23} &\dots & A_{2N} \\
0 & 0 & A_{33} & \ddots & \vdots \\
\vdots & \vdots & \ddots & \ddots & A_{N-1,N} \\
0 & 0 & \dots & 0 & A_{NN}
\end{pmatrix}
\end{equation}
The last row of $\mathbf{A} x = c$ yields an algebraic equation with a single unknown,
\begin{equation}
A_{NN} x_N = c_N \to x_N = \dfrac{A_{NN}}{c_N}.
\end{equation}
With this value known, the second to the last row is also known
\begin{equation}
A_{N-1,N-1}x_{N-1} + A_{N-1,N} x_N = c_{N-1} \to x_{N-1} = \dfrac{1}{A_{N-1,N-1}} \left(c_{N-1} - A_{N-1,N} x_N\right)
\end{equation}
In fact, you should be able to convince yourself of the following recursion relation
\begin{equation}
x_i = \dfrac{1}{A_{i,i}} \left( c_i - \sum_{k = i+1}^N A_{i,k} x_k \right)
\end{equation}

___

Another example is a matrix in lower triangular form. Suppose $\mathbf{A}$ is of the form
\begin{equation}
\mathbf{A} = \begin{pmatrix}
A_{11} & 0 & 0 & \dots & 0 \\
A_{21} & A_{22} & 0 &\dots & 0 \\
A_{31} & A_{32} & A_{33} & \ddots & \vdots \\
\vdots & \vdots & \ddots & \ddots & 0 \\
A{N1} & A_{N2} & \dots & A_{N,N-1} & A_{NN}
\end{pmatrix}
\end{equation}
Following the same logic as before, you should be able to convience yourself that
\begin{equation}
x_i = \dfrac{1}{A_{i,i}} \left( c_i - \sum_{k=1}^{i-1} A_{i,k} x_k \right)
\end{equation}

## <center> Solving a linear set of equations involving lower and upper triangular matrices </center>

In the following, define two functions $\texttt{solveU}$ and $\texttt{solveL}$ which takes as input a upper and lower triangular matrix $\mathbf{U}$ and $\mathbf{L}$ respectively, and a column vector $c$, and respectively solves
\begin{equation}
\mathbf{U} x = c, \qquad \mathbf{L} x = c
\end{equation}

In [2]:
def solveU(U, c):
    n = np.size(c)
    x = np.zeros(n)
    x[-1] = c[-1] / U[-1, -1]
    for i in range(n - 2, -1, -1):
        x[i] = (c[i] - sum(U[i, i: ] * x[i: ])) / U[i, i]
    return x

def solveL(L, c):
    N = len(c)
    x = np.zeros(N)
    for i in range(N):
        x[i] = (1 / L[i, i]) * (c[i] - np.matmul(L[i, :i], x[ :i]))
    return x

Your code should be able to run the following

In [3]:
N = 20
epsilon = 1E-6
detbound = -20
tests = 10

for _ in range(tests):
    
    # selects a random nonsingular matrix
    # do not use N too high, because
    # random nonsingular matrices
    # become rarer and rarer
    while True:
        A = ra.rand(N,N)
        U = np.triu(A)
        if np.log10(la.det(U)) > detbound:
            break
    
    c = ra.rand(N)
    xU = solveU(U,c)
    errorU = np.dot(U,xU) - c
    
    assert abs(np.dot(errorU, errorU)) < epsilon

In [4]:
N = 20
epsilon = 1E-6
detbound = -20
tests = 10

for _ in range(tests):
    
    # selects a random nonsingular matrix
    # do not use N too high, because
    # random nonsingular matrices
    # become rarer and rarer
    while True:
        A = ra.rand(N,N)
        L = np.tril(A)
        if np.log10(la.det(L)) > detbound:
            break
    
    c = ra.rand(N)
    xL = solveL(L,c)
    
    errorL = np.dot(L,xL) - c
    
    assert abs(np.dot(errorL, errorL)) < epsilon

We want the two functions to assume that the inputted matrices are upper and lower triangular matrices, even though they may not be. This is useful later on, when the zeros may actually be floating points which are small - essentially coming from floating point arithmetic

In [5]:
N = 20
epsilon = 1E-6
detbound = -20
tests = 10

for _ in range(tests):
    
    # selects a random nonsingular matrix
    # do not use N too high, because
    # random nonsingular matrices
    # become rarer and rarer
    while True:
        A = ra.rand(N,N)
        U = np.triu(A)
        if np.log10(la.det(U)) > detbound:
            break
    
    c = ra.rand(N)
    xU1 = solveU(U,c)
    xU2 = solveU(A,c)
    errorU = xU1-xU2
    
    assert abs(np.dot(errorU, errorU)) < epsilon

In [6]:
N = 20
epsilon = 1E-6
detbound = -20
tests = 10

for _ in range(tests):
    
    # selects a random nonsingular matrix
    # do not use N too high, because
    # random nonsingular matrices
    # become rarer and rarer
    while True:
        A = ra.rand(N,N)
        L = np.tril(A)
        if np.log10(la.det(L)) > detbound:
            break
    
    c = ra.rand(N)
    xL1 = solveL(L,c)
    xL2 = solveL(A,c)
    errorU = xL1-xL2
    
    assert abs(np.dot(errorL, errorL)) < epsilon

# <center> LU decomposition </center>

There's just one problem: almost all nonsingular matrices $\mathbf{A}$ are neither in upper triangular form and lower triangular form. What the LU decomposition lets us do is follow a deterministic process of factor $\mathbf{A}$ into a product of lower and upper triangular matrices $\mathbf{L}$ and $\mathbf{U}$ respectively.

That is, if we can find a factorization of $\mathbf{A}$ into $\mathbf{L} \mathbf{U}$, then the linear problem
\begin{equation}
\mathbf{A} x = c
\end{equation}
May be translated into
\begin{equation}
\mathbf{L} \mathbf{U} x = c
\end{equation}
Now if we define a new vector $v$ which satisfies
\begin{equation}
\mathbf{L} v = c
\end{equation}
The above equations reduces to two problems involving upper and lower triangular matrices.
\begin{equation}
\mathbf{U} x = v, \qquad \mathbf{L} v = c
\end{equation}
This we already know how to do!

___

The factorization of $\mathbf{A}$ into $\mathbf{L} \mathbf{U}$ proceeds by abusing the identity matrix and associativity. That is, we select a factorization of the identity matrix
\begin{equation}
\ell^{-1}_1 \ell_1 = \mathbb{1}
\end{equation}
such that applying the associative identity on 
\begin{equation}
\mathbb{1} \mathbf{A} = (\ell^{-1}_1 \ell_1) \mathbf{A} = \ell^{-1}_1 (\ell_1 \mathbf{A})
\end{equation}
makes the matrix $\ell_1 \mathbf{A}$ approach an upper triangular matrix and $\ell^{-1}_1$ approaches a lower triangular matrix. Then we do the process again
\begin{equation}
\ell^{-1}_1 \mathbb{1} (\ell_1 \mathbf{A}) = (\ell^{-1}_1 \ell^{-1}_2) (\ell_2 (\ell_1 \mathbf{A}))
\end{equation}
It's useful now to define a sequence of partially triangularized matrices $L^{(n)}$ and $U^{(n)}$, such that
\begin{equation}
L^{(n)} = L^{(n-1)} \ell^{-1}_n, \qquad U^{(n)} = \ell_n U^{(n-1)}
\end{equation}
and define
\begin{equation}
L^{(0)} = \mathbb{1}, \qquad U^{(0)} = A.
\end{equation}
Note the order of operations. Matrix products are associative, not commutative.

All that remains is to define the factorization of $\mathbb{1}$ such that this sequence of matrices terminates with an upper and lower triangular matrix.

## <center> Calculating $\ell_n$ and $U^{(n)}$ </center>

There is an infinite number of ways to create this sequence - most less optimal than others. Here is one: let $\ell_1$ be defined so that it has the most number of 0 possible (sparse to the max) and $U^{(1)}$ be a matrix with its first column looking like its from an upper triangular matrix. If you think hard enough, you might convince yourself that this is the optimal $\ell_1$,
\begin{equation}
\ell_1 = \mathbb{1} + [v^{(1)}, 0, 0, \dots 0]
\end{equation}
where
\begin{equation}
v^{(1)} = \left[0, -\dfrac{U^{(0)}_{2,1}}{U^{(0)}_{1,1}}, - \dfrac{U^{(0)}_{3,1}}{U^{(0)}_{1,1}}, \dots, \dfrac{U^{(0)}_{N,1}}{U^{(0)}_{1,1}} \right] ^T
\end{equation}
Just to be clear,
\begin{equation}
\ell_1 = \begin{pmatrix}
1 & 0 & 0 & \dots & 0 \\
-\dfrac{U^{(0)}_{2,1}}{U^{(0)}_{1,1}} & 1 & 0 & \dots & 0 \\
- \dfrac{U^{(0)}_{3,1}}{U^{(0)}_{1,1}} & 0 & 1 & \ddots & \vdots \\
\vdots & \vdots & \ddots & \ddots & 0 \\
\dfrac{U^{(0)}_{N,1}}{U^{(0)}_{1,1}} & 0 & \dots & 0 & 1
\end{pmatrix}
\end{equation}
Then
\begin{equation}
\ell_1 A = \ell_1 U^{(0)} = U^{(1)} = \begin{pmatrix}
U^{(1)}_{1,1} & U^{(1)}_{1,2} & U^{(1)}_{1,3} & \dots & U^{(1)}_{1,N} \\
0 & U^{(1)}_{2,2} & U^{(1)}_{2,3} & \dots & U^{(1)}_{2,N} \\
0 & U^{(1)}_{3,2} & U^{(1)}_{3,3} & \dots & U^{(1)}_{3,N} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & U^{(1)}_{N,2} & U^{(1)}_{N,3} & \dots & U^{(1)}_{N,N}
\end{pmatrix}
\end{equation}
Then, we do the same thing, defining a sparse-as-possible $\ell_2$ which forces the first two columns of $U^{(2)}$ to look like it comes from a upper triangular matrix.
\begin{equation}
\ell_2 = \mathbb{1} + [0, v_2, 0, \dots, 0]
\end{equation}
where
\begin{equation}
v^{(2)} = \left[0, 0, -\dfrac{U^{(1)}_{3,2}}{U^{(1)}_{2,2}}, -\dfrac{U^{(1)}_{4,2}}{U^{(1)}_{2,2}}, \dots, -\dfrac{U^{(1)}_{N,2}}{U^{(1)}_{2,2}} \right]^T
\end{equation}
___

In general,
\begin{equation}
\ell_n = \mathbb{1} + [0, 0, \dots, v^{(n)}, \dots, 0],
\end{equation}
where $v_n$ is located on the $n$th column and
\begin{equation}
v^{(n)}_k = \left\lbrace \begin{matrix}
0, & k \leq n \\
- \dfrac{U^{(n-1)}_{k,n}}{U^{(n-1)}_{n,n}}, & k > n
\end{matrix}\right.
\end{equation}
and
\begin{equation}
U^{(n)} = \ell_n U^{(n-1)}
\end{equation}

In the following code, let $\texttt{getvn}$ be a function whose inputs is a matrix and an order index $n$, which outputs the column vector above.

In [5]:
def getvn(U, n):
    N = len(U)
    v = np.zeros(N)
    for k in range(n, N):
        v[k] = -U[k, n - 1] / U[n - 1, n - 1]
    return v

The function should pass the following test

In [6]:
testmatrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(testmatrix)

error = 1E-6

assert max(abs(getvn(testmatrix,1)-[0,-5,-9,-13])) < error
assert max(abs(getvn(testmatrix,2)-[0,0,-10/6,-14/6])) < error
assert max(abs(getvn(testmatrix,3)-[0,0,0,-15/11])) < error

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


The next function $\texttt{getelln}$ takes in an arbitrary matrix $U$ and an order index $n$, which return $\ell_n$. Useful functions here are $\texttt{np.identity(n)}$ which produces a $n\times n$ identity matrix.

In [7]:
def getelln(U, n):
    N = len(U)
    vn = getvn(U, n)
    elln = np.zeros((N, N))
    elln[:, n - 1] = vn
    elln += np.identity(N)
    return elln

The function should pass the following test

In [8]:
testmatrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(testmatrix)

error = 1E-6

assert max(abs(getelln(testmatrix,1)[:,0]-[1,-5,-9,-13])) < error
assert max(abs(getelln(testmatrix,2)[:,1]-[0,1,-10/6,-14/6])) < error
assert max(abs(getelln(testmatrix,3)[:,2]-[0,0,1,-15/11])) < error

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Now modify the previous code into a function $\texttt{updateU}$, whose input is a matrix $U$ and an order index $n$, which outputs the pair $v^{(n)}$ and $\ell_n U$

In [9]:
def updateU(U, n):
    vn = getvn(U, n)
    elln = getelln(U, n)
    Unew = np.matmul(elln, U)
    return vn, Unew

The following code should show if $\texttt{updateU}$ results in an upper triangular matrix when applied thrice on a $4 \times 4$ matrix.

In [10]:
U0 = ra.rand(4,4)
print(U0)
v1, U1 = updateU(U0,1)
print(U1)
v2, U2 = updateU(U1,2)
print(U2)
v3, U3 = updateU(U2,3)
print(U3)

[[0.72457194 0.69591637 0.93831619 0.85291926]
 [0.65016648 0.95771851 0.44466839 0.54258952]
 [0.08447921 0.47586543 0.01501006 0.65923845]
 [0.44510926 0.81904775 0.72111244 0.25828835]]
[[ 0.72457194  0.69591637  0.93831619  0.85291926]
 [ 0.          0.33326499 -0.39729318 -0.22274444]
 [ 0.          0.39472722 -0.09439     0.55979499]
 [ 0.          0.39154179  0.14469871 -0.2656655 ]]
[[ 7.24571941e-01  6.95916375e-01  9.38316185e-01  8.52919258e-01]
 [ 0.00000000e+00  3.33264992e-01 -3.97293180e-01 -2.22744436e-01]
 [ 0.00000000e+00 -5.55111512e-17  3.76173782e-01  8.23618956e-01]
 [ 0.00000000e+00  0.00000000e+00  6.11465052e-01 -3.97057709e-03]]
[[ 7.24571941e-01  6.95916375e-01  9.38316185e-01  8.52919258e-01]
 [ 0.00000000e+00  3.33264992e-01 -3.97293180e-01 -2.22744436e-01]
 [ 0.00000000e+00 -5.55111512e-17  3.76173782e-01  8.23618956e-01]
 [ 0.00000000e+00  9.02325749e-17  0.00000000e+00 -1.34275130e+00]]


## <center> Calculating $L^{(n)}$ </center>

One thing we've left out is how $L^{(n)}$ is calculated. Let us recall the recursion,
\begin{equation}
L^{(n)} = L^{(n-1)} \ell^{-1}_n.
\end{equation}
What is nice about the our definition of $\ell_n$ is that
\begin{equation}
\ell^{-1}_n = \mathbb{1} + [0, 0, \dots, -v^{(n)}, \dots, 0]
\end{equation}
Even more convenient (and you should check this) is that
\begin{equation}
L^{(n)} = \mathbb{1} + [-v^{(1)}, -v^{(2)}, \dots, - v^{(n-1)}, - v^{(n)}, 0 \dots, 0]
\end{equation}
In fact our final $L = L^{(N-1)}$ is simply
\begin{equation}
L = \mathbb{1} + [-v^{(1)}, -v^{(2)}, \dots, - v^{(N-2)}, - v^{(N-1)}, 0]
\end{equation}

## <center> Solving linear sets of equations </center>

Now it's finally time to combine everything we know. First, let us define a function $\texttt{getLU}$, whose input is an arbitrary function $\mathbf{A}$ and whose output are two matrices $\mathbf{L}$ and $\mathbf{U}$ which are the LU factorization of $\mathbf{A}$.

Note that for an $N\times N$ matrix, one needs to use $\texttt{updateU}$ $N-1$ times. Also, one can use the vectors outputted by $\texttt{updateU}$ to construct $\mathbf{L}$.

A useful function here is $\texttt{np.copy}$, which lets you copy the values of a matrix, so that mutations on a copied matrix does not affect the original matrix.

In [11]:
def getLU(A):
    N = len(A)
    L = np.zeros((N, N))
    U = np.copy(A)
    for i in range(N - 1):
        vi, U = updateU(U, i + 1)
        L[:, i] = -vi
    L += np.identity(N)
    return L, U

If the factorization is correct, then $\mathbf{L} \mathbf{U} = A$

In [12]:
N = 20
A = ra.rand(N,N)
L,U = getLU(A)

assert la.norm(np.dot(L,U) - A) < 1E-6

Now let's combine everything finally. Given a matrix $\mathbf{A}$ and a constant column vector $c$, we solve for an unknown set of coefficients $x$ constrained by the following set of linear algebraic equations:
\begin{equation}
\mathbf{A} x = c
\end{equation}
We first factorize $\mathbf{A}$ into $\mathbf{L} \mathbf{U}$ and first solve a intermediate set of coefficients $v$
\begin{equation}
\mathbf{L}v = c
\end{equation}
using $\texttt{solveL}$ and then finally $x$
\begin{equation}
\mathbf{U}x = v
\end{equation}
using $\texttt{solveU}$.

Kindly implement this in the following function $\texttt{solveAxc}$, whose inputs are $\mathbf{A}$ and $c$ and whose output is the solution $x$

In [13]:
def solveAxc(A,c):
    L, U = getLU(A)
    v = solveL(L, c)
    x = solveU(U, v)
    return x

Your solution should pass the following unit test.

In [14]:
N = 20
A = ra.rand(N,N)
c = ra.rand(N)
x = solveAxc(A,c)

assert la.norm(np.dot(A,x) - c)<1E-6